[package]
name = "about"
version = "0.1.0"
edition = "2021"
description = "Hello Command Line Attribute Parser!"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
