[workspace]
members = ["crates/*"]
resolver = "2"

[package]
name = "multi-crate-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lints.clippy]
unwrap_used = "deny"
